### ISSUE TITLE
"No delegate votes found for address "

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/ark-ios-monitor#7]
During loging I use my delegate address "AbUdMhk96FbzxH7vDYAwdyqUELmLopZV5x", unfortunately app doesn't recognize any delegate here.

**Comment by vrlcrypt** [comment]
@biolypl, thank you for reporting this issue. We will fix it.
For now, if you vote for your delegate from your delegate address, you can see your statistics.

**Comment by biolypl** [comment]
Thank you, after vote working like a charm :)

**Comment by vrlc92** [comment]
Great, anyway, we will fix this problem.

**Comment by Awalz** [comment]
I don't think this is an issue. Delegate jamie reported the same thing. The Delegate page is to view the status of your delegate. Seems like @biolypl hadn't voted for any delegates, and thus it was not showing. 

We could have a fallback for accounts tied to Delegates, but since Delegates to not need to vote for themselves, who would we show? The Delegate, or the vote of the Delegate.

Ill have to think about this one
